model:
  class_path: embeddings.models.SimpleConv
  init_args:
    n_channels: 3
    n_classes: 10
    kernel_size: 3
data:
  class_path: embeddings.dataloaders.PixelEmbeddingDataModule
  init_args:
    batch_size: 32